"""
Abstract storage backend for background response payloads.

Implementations must be thread-safe: write() and read() may be called from
background worker threads while the main Flask thread is still running.
"""
from abc import ABC, abstractmethod
from typing import Optional


class StorageBackend(ABC):
    """
    Abstract interface for storing and retrieving background response files.

    Each background response uses two keys:
      input_key  — stores the original /v1/responses request payload (JSON)
      output_key — stores the formatted response (JSON), written when completed

    The meaning of a "key" is implementation-specific:
      - LocalStorageBackend: key is a filesystem path (str)
      - S3StorageBackend:    key is an S3 object key (str), bucket is configured separately

    Keys are generated by the gateway and stored in the BackgroundResponse DB record
    so that any instance (or process) can later resolve them via read().
    """

    @abstractmethod
    def write(self, key: str, content: str) -> None:
        """
        Persist *content* under *key*.

        Args:
            key:     Storage key / path / object name.
            content: UTF-8 string to store (typically JSON).

        Raises:
            OSError / botocore.exceptions.ClientError on failure.
        """

    @abstractmethod
    def read(self, key: str) -> Optional[str]:
        """
        Retrieve the content stored under *key*.

        Args:
            key: Storage key / path / object name.

        Returns:
            The stored string, or ``None`` if the key does not exist.

        Raises:
            OSError / botocore.exceptions.ClientError on unexpected errors
            (key-not-found should be swallowed and returned as None).
        """

    @abstractmethod
    def make_key(self, response_id: str, suffix: str) -> str:
        """
        Build a storage key for a given response_id and file suffix.

        Args:
            response_id: The background response identifier (e.g. "resp_xxxx").
            suffix:      File type hint, e.g. "input" or "output".

        Returns:
            A string key suitable for write() / read().
        """
