steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    dir: 'backend'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/yunzhuqing-model-link/${_IMAGE_NAME}:${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/yunzhuqing-model-link/${_IMAGE_NAME}:latest'
      - '.'

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '--all-tags'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/yunzhuqing-model-link/${_IMAGE_NAME}'

images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/yunzhuqing-model-link/${_IMAGE_NAME}:${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/yunzhuqing-model-link/${_IMAGE_NAME}:latest'

substitutions:
  _REGION: 'asia-southeast1'
  _IMAGE_NAME: 'model-link'

options:
  logging: CLOUD_LOGGING_ONLY
