"""add support_thinking field in ml_models

Revision ID: 041c7168af5e
Revises: b1d9b951067f
Create Date: 2026-03-18 21:31:49.846734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '041c7168af5e'
down_revision = 'b1d9b951067f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if index already exists before creating (handles MySQL where it may already exist)
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_indexes = [idx['name'] for idx in inspector.get_indexes('ml_models')]
    
    if 'ix_ml_models_alias' not in existing_indexes:
        with op.batch_alter_table('ml_models', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_ml_models_alias'), ['alias'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_models_alias'))

    # ### end Alembic commands ###
