"""add credits and credit_price_unit to usage_records

Revision ID: 07a532f3f07b
Revises: 6d7fbe925a04
Create Date: 2026-05-11 14:35:51.651505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a532f3f07b'
down_revision = '6d7fbe925a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_usage_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits', sa.Numeric(precision=20, scale=10), nullable=True))
        batch_op.add_column(sa.Column('credit_price_unit', sa.Numeric(precision=20, scale=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_usage_records', schema=None) as batch_op:
        batch_op.drop_column('credit_price_unit')
        batch_op.drop_column('credits')

    # ### end Alembic commands ###
