"""add thinking records table

Revision ID: 08a0358306d4
Revises: f1a2b3c4d5e6
Create Date: 2026-05-24 20:46:55.222931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08a0358306d4'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_thinking_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('thinking_id', sa.String(length=200), nullable=False),
    sa.Column('thinking_signature', sa.Text(), nullable=True),
    sa.Column('thinking_content', sa.Text(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_thinking_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_thinking_records_thinking_id'), ['thinking_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_thinking_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_thinking_records_thinking_id'))

    op.drop_table('ml_thinking_records')
    # ### end Alembic commands ###
