"""Add tags field to provider for billing usage binding

Revision ID: 0f45452122a5
Revises: n0o1p2q3r4s5
Create Date: 2026-03-29 09:52:31.242350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f45452122a5'
down_revision = 'n0o1p2q3r4s5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
