"""add_authorization_field_to_provider

Revision ID: 1f90c0ba0b8c
Revises: 2a4e5e4595a4
Create Date: 2026-03-29 21:13:23.830224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f90c0ba0b8c'
down_revision = '2a4e5e4595a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorization', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.drop_column('authorization')

    # ### end Alembic commands ###
