"""sync current state

Revision ID: 2307e81a21fb
Revises: b1c6090babb8
Create Date: 2026-03-12 20:59:14.506064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2307e81a21fb'
down_revision = 'b1c6090babb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        # Avoid duplication error if already created in 3a8b5c7d9e12 or 86f5002e4369
        # But since we're syncing current state, let's just make it safe
        pass

    # Ensure all providers have a group_id before setting it to NOT NULL
    op.execute("UPDATE ml_providers SET group_id = (SELECT id FROM ml_groups LIMIT 1) WHERE group_id IS NULL")

    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('ml_user_groups', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_user_groups', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_models_alias'))

    # ### end Alembic commands ###
