"""sync database with models

Revision ID: 2a4e5e4595a4
Revises: 92ea386ad62e
Create Date: 2026-03-29 16:34:49.255067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4e5e4595a4'
down_revision = '92ea386ad62e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_size', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reasoning_effort', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('supported_image_formats', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pricing_tiers', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('retirement_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rpm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tpm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('support_online_image', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('support_online_video', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('support_embedding', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_column('support_embedding')
        batch_op.drop_column('support_online_video')
        batch_op.drop_column('support_online_image')
        batch_op.drop_column('discount')
        batch_op.drop_column('tpm')
        batch_op.drop_column('rpm')
        batch_op.drop_column('retirement_time')
        batch_op.drop_column('currency')
        batch_op.drop_column('pricing_tiers')
        batch_op.drop_column('supported_image_formats')
        batch_op.drop_column('reasoning_effort')
        batch_op.drop_column('output_size')

    # ### end Alembic commands ###
