"""sync_database_with_models

Revision ID: 2c9f01a961c9
Revises: w2b3c4d5e6f7
Create Date: 2026-05-05 12:56:50.005205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9f01a961c9'
down_revision = 'w2b3c4d5e6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_permissions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_permission_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_ml_permissions_key'))
        batch_op.create_index(batch_op.f('ix_ml_permissions_key'), ['key'], unique=True)

    with op.batch_alter_table('ml_users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_ml_users_id'), ['id'], unique=False)

    with op.batch_alter_table('ml_workspaces', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ml_workspaces_name_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_ml_workspaces_name'))
        batch_op.create_index(batch_op.f('ix_ml_workspaces_name'), ['name'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_workspaces_name'))
        batch_op.create_index(batch_op.f('ix_ml_workspaces_name'), ['name'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('ml_workspaces_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('ml_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_users_id'))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('ml_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_permissions_key'))
        batch_op.create_index(batch_op.f('ix_ml_permissions_key'), ['key'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_permission_key'), ['key'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
