"""add type field to provider

Revision ID: 2d75af3cf634
Revises: 4a7e577f9ada
Create Date: 2026-03-11 20:43:56.788814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d75af3cf634'
down_revision = '4a7e577f9ada'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE ml_providers SET type = 'openai' WHERE type IS NULL")
    
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.alter_column('type', type_=sa.String(length=50), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
