"""add service_tiers to model templates

Revision ID: 3a46d9278993
Revises: b989821db7b2
Create Date: 2026-08-05 09:18:19.752535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a46d9278993'
down_revision = 'b989821db7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_model_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_tiers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_model_templates', schema=None) as batch_op:
        batch_op.drop_column('service_tiers')

    # ### end Alembic commands ###
