"""add alias field to model

Revision ID: 3a8b5c7d9e12
Revises: 2d75af3cf634
Create Date: 2026-03-12 11:07:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8b5c7d9e12'
down_revision = '2d75af3cf634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alias', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_ml_models_alias'), ['alias'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_models_alias'))
        batch_op.drop_column('alias')

    # ### end Alembic commands ###
