"""uploaded_files: add storage_key and provider_id

Revision ID: 497ad4adde1f
Revises: c1d2e3f4a5b6
Create Date: 2026-07-09 09:36:14.685046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497ad4adde1f'
down_revision = 'c1d2e3f4a5b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_uploaded_files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage_key', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_ml_uploaded_files_provider_id'), ['provider_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_uploaded_files_provider_id'))
        batch_op.drop_column('provider_id')
        batch_op.drop_column('storage_key')

    # ### end Alembic commands ###
