"""Initial migration

Revision ID: 4a7e577f9ada
Revises: 
Create Date: 2026-03-10 10:05:26.234207

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a7e577f9ada'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_groups_name'), ['name'], unique=True)

    op.create_table('ml_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_providers_name'), ['name'], unique=True)

    op.create_table('ml_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_ml_users_username'), ['username'], unique=True)

    op.create_table('ml_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ml_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_api_keys_key'), ['key'], unique=True)

    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('context_size', sa.Integer(), nullable=True),
    sa.Column('input_size', sa.Integer(), nullable=True),
    sa.Column('input_price', sa.Float(), nullable=True),
    sa.Column('output_price', sa.Float(), nullable=True),
    sa.Column('cache_creation_price', sa.Float(), nullable=True),
    sa.Column('cache_hit_price', sa.Float(), nullable=True),
    sa.Column('support_kvcache', sa.Boolean(), nullable=True),
    sa.Column('support_image', sa.Boolean(), nullable=True),
    sa.Column('support_audio', sa.Boolean(), nullable=True),
    sa.Column('support_video', sa.Boolean(), nullable=True),
    sa.Column('support_file', sa.Boolean(), nullable=True),
    sa.Column('support_web_search', sa.Boolean(), nullable=True),
    sa.Column('support_tool_search', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ml_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_models_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_models_name'), ['name'], unique=False)

    op.create_table('ml_user_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['ml_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ml_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # Note: Only creating ml_* tables, not dropping any existing tables
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_meta_data',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('teamspace', mysql.VARCHAR(length=64), nullable=False, comment='团队空间标识'),
    sa.Column('model_code', mysql.VARCHAR(length=64), nullable=False, comment='模型业务标识'),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False, comment='模型显示名称'),
    sa.Column('description', mysql.VARCHAR(length=1024), nullable=True, comment='描述'),
    sa.Column('creator', mysql.VARCHAR(length=64), nullable=False, comment='创建人 LDAP'),
    sa.Column('channel', mysql.VARCHAR(length=32), nullable=False, comment='来源渠道 (UPLOAD/TRAINING)'),
    sa.Column('test_clusters', mysql.JSON(), nullable=True, comment='测试环境集群列表 (List<Integer>)'),
    sa.Column('stage', mysql.VARCHAR(length=32), nullable=False, comment='当前阶段 (BETA/PROD)'),
    sa.Column('bpm_id', mysql.VARCHAR(length=64), nullable=True, comment='当前关联的审批流 ID'),
    sa.Column('files', mysql.TEXT(), nullable=True, comment='当前文件列表映射 (List<ModelFile>)'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='逻辑删除标记'),
    sa.Column('created', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='修改时间'),
    sa.Column('custom_path', mysql.VARCHAR(charset='utf8', length=255), nullable=True, comment='custom_path'),
    sa.PrimaryKeyConstraint('id'),
    comment='模型元数据表',
    mysql_comment='模型元数据表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('model_meta_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uk_teamspace_model_code'), ['teamspace', 'model_code'], unique=True)

    op.create_table('vs_datasource_info',
    sa.Column('datasource_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='自动递增主键'),
    sa.Column('datasource_info', mysql.VARCHAR(length=2048), nullable=False, comment='数据源描述，包括数据源类型、表名、hive表sql范围等信息'),
    sa.Column('datasource_hash', mysql.VARCHAR(length=255), nullable=True, comment='数据源描述的哈希值'),
    sa.Column('embedding_dimension', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='embedding维度'),
    sa.Column('embedding_model_name', mysql.VARCHAR(length=255), nullable=False, comment='embedding的模型名称'),
    sa.Column('neverland_task_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True, comment='neverland调度任务的id'),
    sa.Column('hbase_table_name', mysql.VARCHAR(length=255), nullable=True, comment='metadata及embedding存储的表名'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否已删除'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('datasource_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('vs_datasource_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_neverland_task_id'), ['neverland_task_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_datasource_hash'), ['datasource_hash'], unique=False)

    op.create_table('agent_classification_scene_mapping',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='唯一标识'),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='类型 0:文本 1:图片 2:其他'),
    sa.Column('classification_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='分类id'),
    sa.Column('scene_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='场景id'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='agent 分类场景的映射关系',
    mysql_comment='agent 分类场景的映射关系',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('agent_classification_scene_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_type_classification_id'), ['type', 'classification_id'], unique=False)

    op.create_table('logs',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('type', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('content', mysql.LONGTEXT(), nullable=True),
    sa.Column('username', mysql.VARCHAR(length=191), server_default=sa.text("''"), nullable=True),
    sa.Column('token_name', mysql.VARCHAR(length=191), server_default=sa.text("''"), nullable=True),
    sa.Column('model_name', mysql.VARCHAR(length=191), server_default=sa.text("''"), nullable=True),
    sa.Column('quota', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('prompt_tokens', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('completion_tokens', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('channel_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('request_id', mysql.VARCHAR(length=191), server_default=sa.text("''"), nullable=True),
    sa.Column('elapsed_time', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('is_stream', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('system_prompt_reset', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('index_username_model_name'), ['model_name', 'username'], unique=False)
        batch_op.create_index(batch_op.f('idx_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_logs_token_name'), ['token_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_logs_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_logs_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_created_at_type'), ['created_at', 'type'], unique=False)

    op.create_table('tokens',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('key', mysql.CHAR(length=90), nullable=True),
    sa.Column('status', mysql.BIGINT(display_width=20), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('created_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('accessed_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('expired_time', mysql.BIGINT(display_width=20), server_default=sa.text("'-1'"), autoincrement=False, nullable=True),
    sa.Column('remain_quota', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('unlimited_quota', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('used_quota', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('flow_ctl_qpm', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('models', mysql.TEXT(), nullable=True),
    sa.Column('subnet', mysql.VARCHAR(length=191), server_default=sa.text("''"), nullable=True),
    sa.Column('daily_quota', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('daily_used_quota', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('daily_quota_reset_time', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tokens_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_tokens_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('idx_flow_ctl_qpm'), ['flow_ctl_qpm'], unique=False)

    op.create_table('training_teamspace_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('teamspace_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='teamspace主键'),
    sa.Column('ldap', mysql.VARCHAR(length=20), nullable=False, comment='ldpa name'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False, comment='逻辑删除'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('training_teamspace_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('teamspace_ldap_unique'), ['teamspace_id', 'ldap'], unique=True)

    op.create_table('llm_user_group_relation',
    sa.Column('owner', mysql.VARCHAR(length=255), nullable=False, comment='团队所有者花名拼音'),
    sa.Column('follower', mysql.VARCHAR(length=255), nullable=False, comment='团队成员花名拼音'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('owner', 'follower'),
    comment='https://cf.qunhequnhe.com/pages/viewpage.action?pageId=80905478945',
    mysql_comment='https://cf.qunhequnhe.com/pages/viewpage.action?pageId=80905478945',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llm_user_group_relation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_follower'), ['follower'], unique=False)

    op.create_table('vs_task_datasource_relationship',
    sa.Column('taskid', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='向量平台的任务id'),
    sa.Column('datasource_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='数据源id'),
    sa.Column('datasource_type', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='数据源类型，0：全量数据源；1：增量数据源'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否已删除'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('taskid', 'datasource_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('vs_task_datasource_relationship', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_datasource_type'), ['datasource_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_datasource_id'), ['datasource_id'], unique=False)

    op.create_table('memory_history',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False, comment='UUID 主键'),
    sa.Column('memory_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False, comment='关联的记忆ID'),
    sa.Column('old_memory', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='旧记忆内容'),
    sa.Column('new_memory', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='新记忆内容'),
    sa.Column('event', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False, comment='事件类型（add/update/delete）'),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后更新时间'),
    sa.Column('is_deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否删除（软删除标志）'),
    sa.Column('actor_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='操作者ID（可选）'),
    sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True, comment='角色（user/assistant/system）'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('memory_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_memory_id'), ['memory_id'], unique=False)

    op.create_table('knowledgebase_meta',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='自动递增主键'),
    sa.Column('knowledge_name', mysql.VARCHAR(length=255), nullable=False, comment='知识库名称'),
    sa.Column('knowledge_desc', mysql.TEXT(), nullable=True, comment='知识库描述'),
    sa.Column('creator', mysql.VARCHAR(length=255), nullable=False, comment='创建者的LDAP花名拼音'),
    sa.Column('last_modifier', mysql.VARCHAR(length=255), nullable=True, comment='最后修改者的LDAP花名拼音'),
    sa.Column('ann_index_name', mysql.VARCHAR(length=255), nullable=True, comment='ANN索引名，创建知识库时按规则生成'),
    sa.Column('embedding_model_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='embedding模型id，创建时选择；业务上作为外键与embedding模型信息表关联'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否已删除'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('knowledgebase_meta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_lastmodified'), ['lastmodified'], unique=False)
        batch_op.create_index(batch_op.f('idx_embedding_model_id'), ['embedding_model_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_creator'), ['creator'], unique=False)
        batch_op.create_index(batch_op.f('idx_created'), ['created'], unique=False)

    op.create_table('knowledge_datasource_hive_meta',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='自动递增主键'),
    sa.Column('knowledgebase_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='所属的知识库id，业务上作为外键与知识库元信息表关联'),
    sa.Column('chunk_type', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='文本内容分片方式，0：不分片；1：自动分片；2：指定长度；3：指定分割符'),
    sa.Column('chunk_size', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='文本分片长度'),
    sa.Column('full_table_name', mysql.VARCHAR(length=255), nullable=True, comment='全量表的完整表名，包括项目名'),
    sa.Column('full_title_fields', mysql.VARCHAR(length=511), nullable=True, comment='全量表标题字段列表，英文逗号分割'),
    sa.Column('full_content_fields', mysql.VARCHAR(length=511), nullable=True, comment='全量表内容字段列表，英文逗号分割'),
    sa.Column('full_url_fields', mysql.VARCHAR(length=511), nullable=True, comment='全量表URL字段列表，英文逗号分隔'),
    sa.Column('full_filter_sql', mysql.TEXT(), nullable=True, comment='用于圈选全量数据的SQL过滤语句'),
    sa.Column('need_delta', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否需要增量调度更新'),
    sa.Column('delta_table_name', mysql.VARCHAR(length=255), nullable=True, comment='增量表的完整表名，包括项目名'),
    sa.Column('delta_title_fields', mysql.VARCHAR(length=511), nullable=True, comment='增量表标题字段列表，英文逗号分割'),
    sa.Column('delta_content_fields', mysql.VARCHAR(length=511), nullable=True, comment='增量表内容字段列表，英文逗号分割'),
    sa.Column('delta_url_fields', mysql.VARCHAR(length=511), nullable=True, comment='增量表URL字段列表，英文逗号分隔'),
    sa.Column('delta_filter_sql', mysql.TEXT(), nullable=True, comment='用于圈选增量数据的SQL过滤语句'),
    sa.Column('delta_job_param_str', mysql.VARCHAR(length=511), nullable=True, comment='创建数栈任务时的参数配置，格式为"key1=format1,key2=format2"，format格式直接对齐到底层的数栈任务；如："ds=${yyyyMMdd},ds2=${yyyyMMdd-1}"'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否已删除'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='数据源名称'),
    sa.Column('chunk_separator', mysql.VARCHAR(length=255), server_default=sa.text("'\\n'"), nullable=True, comment='文本分片分割符，多项以;分割'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('knowledge_datasource_hive_meta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_lastmodified'), ['lastmodified'], unique=False)
        batch_op.create_index(batch_op.f('idx_knowledge_id'), ['knowledgebase_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_created'), ['created'], unique=False)

    op.create_table('vs_task_info',
    sa.Column('taskid', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='向量平台taskid'),
    sa.Column('ann_engine_type', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='向量引擎类型，0：自建milvus向量引擎，1：es8向量引擎'),
    sa.Column('ann_index_name', mysql.VARCHAR(length=255), nullable=False, comment='向量引擎索引名字'),
    sa.Column('ann_index_instance_name', mysql.VARCHAR(length=255), nullable=True, comment='向量引擎索引最新实例名字'),
    sa.Column('embedding_dimension', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='embedding维度'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否已删除'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.Column('call_back_url', mysql.VARCHAR(length=511), nullable=True, comment='向量平台回调业务方url'),
    sa.PrimaryKeyConstraint('taskid'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('vs_task_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ann_index_name'), ['ann_index_name'], unique=True)
        batch_op.create_index(batch_op.f('idx_ann_engine_type'), ['ann_engine_type'], unique=False)

    op.create_table('vs_datasource_status',
    sa.Column('datasource_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='数据源id'),
    sa.Column('status', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='数据源调度状态，0：全量调度开始；1：全量调度完成，2：全量调度失败'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否已删除'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('datasource_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('vs_datasource_status', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)

    op.create_table('vector_app_token',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='唯一标识'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True, comment='app token 名称'),
    sa.Column('vector_app_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='vector_app 对应的ID'),
    sa.Column('token', mysql.VARCHAR(length=2048), nullable=False, comment='访问另外'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='逻辑删除标识字段'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='vector_app 访问令牌',
    mysql_comment='vector_app 访问令牌',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('vector_app_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_vector_app_id'), ['vector_app_id'], unique=False)

    op.create_table('rag_scene',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='自动递增主键'),
    sa.Column('knowledgebase_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True, comment='关联知识库id'),
    sa.Column('llm_model_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=True, comment='LLM模型id'),
    sa.Column('prompt_template', mysql.TEXT(), nullable=False, comment='prompt模板'),
    sa.Column('system_prompt', mysql.TEXT(), nullable=True, comment='系统消息，可为LLM模型指定角色，引导回答方向，如“你是一个非常聪明的AI助手”'),
    sa.Column('topk', mysql.INTEGER(display_width=11), server_default=sa.text("'3'"), autoincrement=False, nullable=False, comment='召回topK'),
    sa.Column('low_threshold', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0.1'"), nullable=False, comment='低相关性阈值参数'),
    sa.Column('low_threshold_template', mysql.TEXT(), nullable=True, comment='相关性过低时展示的信息，如“根据已知信息无法回答该问题，您是否想问关于{title}的问题”'),
    sa.Column('high_threshold', mysql.DOUBLE(asdecimal=True), server_default=sa.text("'0.9'"), nullable=False, comment='高相关性阈值参数'),
    sa.Column('need_image_process', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否需要图文处理逻辑'),
    sa.Column('need_output_detect', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='输出内容是否开启同盾检测'),
    sa.Column('need_input_detect', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='输入内容是否开启同盾检测'),
    sa.Column('need_related_content_show', mysql.TINYINT(display_width=4), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='大模型回答的参考内容是否展示'),
    sa.Column('creator', mysql.VARCHAR(length=255), nullable=False, comment='创建者的LDAP花名拼音'),
    sa.Column('last_modifier', mysql.VARCHAR(length=255), nullable=True, comment='最后修改者的LDAP花名拼音'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否已删除'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='场景名称'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('rag_scene', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_llm_model_id'), ['llm_model_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_lastmodified'), ['lastmodified'], unique=False)
        batch_op.create_index(batch_op.f('idx_knowledgebase_id'), ['knowledgebase_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_creator'), ['creator'], unique=False)
        batch_op.create_index(batch_op.f('idx_created'), ['created'], unique=False)

    op.create_table('training_teamspace',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='自增id'),
    sa.Column('name', mysql.VARCHAR(length=15), nullable=False, comment='teamspace名称'),
    sa.Column('cmdbtag', mysql.VARCHAR(length=255), nullable=False, comment='cmdbtag'),
    sa.Column('descript', mysql.TEXT(), nullable=False, comment='描述'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False, comment='逻辑删除'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='记录teamspace信息',
    mysql_comment='记录teamspace信息',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('training_teamspace', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('content_fragment',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='分片唯一标识'),
    sa.Column('fragment', mysql.TEXT(), nullable=False, comment='文章分片'),
    sa.Column('record_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='上传记录id'),
    sa.Column('scene', mysql.VARCHAR(length=255), nullable=False, comment='接入的业务场景，对应不同的大语言模型配置'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False, comment='逻辑删除标识'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='文章分片表',
    mysql_comment='文章分片表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('content_fragment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('RECORD_SCENE_IDX'), ['record_id', 'scene'], unique=False)

    op.create_table('resource_refs',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('key', mysql.VARCHAR(length=512), nullable=False),
    sa.Column('ds', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('created', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('last_modified', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('resource_refs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_resource_refs_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('idx_resource_refs_ds'), ['ds'], unique=False)

    op.create_table('history',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('memory_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('old_memory', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('new_memory', mysql.LONGTEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('event', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('is_deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('actor_id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('training_teamspace_cluster',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='自增id'),
    sa.Column('teamspace_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='training_teamspace主键'),
    sa.Column('cluster', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='机房 0矩阵 1中卫 2鄂尔多斯 3哈尔滨， 具体见：https://cf.qunhequnhe.com/pages/viewpage.action?pageId=81271482090'),
    sa.Column('gpu_quota', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='gpu配额'),
    sa.Column('storage_quota', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='存储配额'),
    sa.Column('cpu_quota', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='cpu配额'),
    sa.Column('memory_quota', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='内存配额'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), autoincrement=False, nullable=False, comment='逻辑删除'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('training_teamspace_cluster', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('teamspace_cluster_unique'), ['teamspace_id', 'cluster'], unique=True)

    op.create_table('channels',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('type', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('key', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.BIGINT(display_width=20), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('weight', mysql.BIGINT(display_width=20, unsigned=True), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('test_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('response_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('base_url', mysql.VARCHAR(length=191), server_default=sa.text("''"), nullable=True),
    sa.Column('other', mysql.LONGTEXT(), nullable=True),
    sa.Column('balance', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('balance_updated_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('models', mysql.LONGTEXT(), nullable=True),
    sa.Column('group', mysql.VARCHAR(length=512), server_default=sa.text("'default'"), nullable=True),
    sa.Column('used_quota', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('model_mapping', mysql.VARCHAR(length=4096), server_default=sa.text("''"), nullable=True),
    sa.Column('priority', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('config', mysql.LONGTEXT(), nullable=True),
    sa.Column('system_prompt', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_channels_name'), ['name'], unique=False)

    op.create_table('agent_project_input_format_mapping',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='唯一标识'),
    sa.Column('project_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='项目id'),
    sa.Column('input_format_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='输入格式id'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='项目与格式的映射关系',
    mysql_comment='项目与格式的映射关系',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('agent_project_input_format_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_format_id'), ['input_format_id'], unique=False)

    op.create_table('vector_app',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='APP名称'),
    sa.Column('embedding_model', mysql.VARCHAR(length=255), nullable=True, comment='embedding 模型，可以为空，也可能是业务端自己构造的vector，不需要经过embedding模型'),
    sa.Column('metric_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='度量类型'),
    sa.Column('dimension', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='维度数'),
    sa.Column('model_link_token', mysql.VARCHAR(length=255), nullable=True, comment='model link 访问令牌，也可能是业务端自己构造的vector，不需要经过embedding模型'),
    sa.Column('model_link_channel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='model link 对应的渠道'),
    sa.Column('index_name', mysql.VARCHAR(length=255), nullable=False, comment='存储对应的索引名称'),
    sa.Column('storage_type', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='存储类型 0:milvus 1: es'),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True, comment='描述'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='逻辑删除标识'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.Column('user_id', mysql.VARCHAR(length=255), nullable=False, comment='所属的用户ID'),
    sa.Column('authority', mysql.TEXT(charset='utf8mb4'), nullable=True, comment='向量数据库鉴权信息'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('vector_app', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('index_user_id'), ['user_id'], unique=False)

    op.create_table('extend_datasource_mapping',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('dsid', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='业务数据源id'),
    sa.Column('dstype', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='数据源类型，枚举值：\n0：hive表数据源'),
    sa.Column('map_dsid', mysql.VARCHAR(length=511), nullable=False, comment='外部数据源id'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.Column('extra_info', mysql.VARCHAR(length=511), nullable=True, comment='额外信息标识，比如Hive数据源是否是增量表'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否已删除'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('extend_datasource_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_map_dsid'), ['map_dsid'], unique=False)
        batch_op.create_index(batch_op.f('idx_lastmodified'), ['lastmodified'], unique=False)
        batch_op.create_index(batch_op.f('idx_dsid_dstype'), ['dsid', 'dstype'], unique=False)
        batch_op.create_index(batch_op.f('idx_created'), ['created'], unique=False)

    op.create_table('vector_field_embedding',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='自增id'),
    sa.Column('vector_app_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='vector_app表主键id'),
    sa.Column('field_name', mysql.VARCHAR(charset='utf8mb4', length=255), nullable=False, comment='向量字段名称'),
    sa.Column('embedding_model', mysql.VARCHAR(charset='utf8mb4', length=255), nullable=False, comment='embedding模型名称'),
    sa.Column('metric_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='度量类型'),
    sa.Column('dimension', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='维度'),
    sa.Column('model_link_token', mysql.VARCHAR(charset='utf8mb4', length=255), nullable=False, comment='model link 访问令牌，也可能是业务端自己构造的vector，不需要经过embedding模型'),
    sa.Column('model_link_channel', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='model link 对应的渠道'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='逻辑删除标识'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('vector_field_embedding', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_app_field'), ['vector_app_id', 'field_name'], unique=True)

    op.create_table('datasource_status_record',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='自动递增主键'),
    sa.Column('dsid', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='数据源id'),
    sa.Column('dstype', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='数据源类型，枚举值；0：hive表数据源'),
    sa.Column('task_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='调度任务id'),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='任务状态，枚举值；0：初始化；1：全量加载中；2：全量加载失败；3：全量加载成功；4：增量加载中；5：增量加载失败；6：增量加载成功；7：删除中；8：删除失败；9：删除成功'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='数据源状态记录表',
    mysql_comment='数据源状态记录表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('datasource_status_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_lastmodified'), ['lastmodified'], unique=False)
        batch_op.create_index(batch_op.f('idx_dsid_dstype'), ['dsid', 'dstype'], unique=False)
        batch_op.create_index(batch_op.f('idx_created'), ['created'], unique=False)

    op.create_table('id_generator',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('max_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='当前最大id'),
    sa.Column('step', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='号段的步长'),
    sa.Column('task_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='对应向量平台的任务id'),
    sa.Column('version', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='版本号'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('transfer_job_record',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='自增ID'),
    sa.Column('k8s_job_name', mysql.VARCHAR(length=128), nullable=False, comment='K8s中的Job Name'),
    sa.Column('dst_cluster', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='目标机房ID (ClusterEnum)'),
    sa.Column('src_files', mysql.TEXT(), nullable=False, comment='源文件列表(JSON)'),
    sa.Column('dst_directory', mysql.VARCHAR(length=512), nullable=False, comment='目标存储目录'),
    sa.Column('status', mysql.VARCHAR(length=32), nullable=False, comment='PENDING, RUNNING, SUCCEEDED, FAILED'),
    sa.Column('submitter', mysql.VARCHAR(length=64), nullable=True, comment='提交人'),
    sa.Column('created', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('lastmodified', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.Column('teamspace', mysql.VARCHAR(length=64), nullable=False, comment='teamspace'),
    sa.Column('model_code', mysql.VARCHAR(length=64), nullable=False, comment='model_code'),
    sa.PrimaryKeyConstraint('id'),
    comment='跨机房数据流转任务表',
    mysql_comment='跨机房数据流转任务表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('transfer_job_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_submitter'), ['submitter'], unique=False)
        batch_op.create_index(batch_op.f('idx_status'), ['status'], unique=False)

    op.create_table('redemptions',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('key', mysql.CHAR(length=32), nullable=True),
    sa.Column('status', mysql.BIGINT(display_width=20), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('quota', mysql.BIGINT(display_width=20), server_default=sa.text("'100'"), autoincrement=False, nullable=True),
    sa.Column('created_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('redeemed_time', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('redemptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_redemptions_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('idx_redemptions_key'), ['key'], unique=True)

    op.create_table('model_features',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('channel_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('model_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('supports_max_completion_tokens', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('supports_reasoning_effort', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('supports_function_call', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('supports_image_input', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('supports_audio_input', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('support_web_search', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('support_image_generation', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('response_format', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('prompt_caching', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('lastmodified', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('model_features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_model_name'), ['model_name'], unique=False)

    op.create_table('knowledge_chat_message',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('role', mysql.VARCHAR(length=100), nullable=False, comment='对话角色, user , assistant'),
    sa.Column('message', mysql.TEXT(charset='utf8mb4'), nullable=False, comment='对话内容'),
    sa.Column('session_id', mysql.VARCHAR(length=512), nullable=True, comment='会话id'),
    sa.Column('user_id', mysql.VARCHAR(length=64), nullable=False, comment='用户id'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='逻辑删除标识'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.Column('chat_id', mysql.VARCHAR(length=512), nullable=False, comment='对话id'),
    sa.PrimaryKeyConstraint('id'),
    comment='知识库历史对话记录表',
    mysql_comment='知识库历史对话记录表',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('knowledge_chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_created'), ['created'], unique=False)

    op.create_table('model_meta_data_history',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('model_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='关联 model_meta_data.id'),
    sa.Column('version_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='版本号'),
    sa.Column('files', mysql.JSON(), nullable=True, comment='发布时的文件快照'),
    sa.Column('release_note', mysql.VARCHAR(length=1024), nullable=True, comment='发布说明'),
    sa.Column('bpm_id', mysql.VARCHAR(length=64), nullable=True, comment='关联的审批流 ID'),
    sa.Column('created', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='模型发布历史表',
    mysql_comment='模型发布历史表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('model_meta_data_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_model_id'), ['model_id'], unique=False)

    op.create_table('memory_sequence',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='主键ID'),
    sa.Column('current_app_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='当前应用id'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('rag_scene_apptoken',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='自动递增主键'),
    sa.Column('token', mysql.VARCHAR(length=2048), nullable=False, comment='业务方接入用的token，JWT加密字符串'),
    sa.Column('rag_scene_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='RAG场景id'),
    sa.Column('creator', mysql.VARCHAR(length=255), nullable=True, comment='token创建者LDAP花名拼音'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='token名称'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('rag_scene_apptoken', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_token'), ['token'], unique=False, mysql_length={'token': 768})
        batch_op.create_index(batch_op.f('idx_rag_scene_id'), ['rag_scene_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_lastmodified'), ['lastmodified'], unique=False)
        batch_op.create_index(batch_op.f('idx_created'), ['created'], unique=False)

    op.create_table('embedding_info',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False, comment='自动递增主键'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True, comment='embedding模型名称'),
    sa.Column('dimension', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='embeddng维度'),
    sa.Column('algorithm', mysql.VARCHAR(length=255), nullable=True, comment='embedding算法名称'),
    sa.Column('one_api_token', mysql.TEXT(), nullable=False, comment='用于访问one-api的token'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否已删除'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.Column('public', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否公开'),
    sa.Column('owner', mysql.VARCHAR(length=255), nullable=True, comment='owner的LDAP花名拼音'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('embedding_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_lastmodified'), ['lastmodified'], unique=False)
        batch_op.create_index(batch_op.f('idx_created'), ['created'], unique=False)

    op.create_table('evaluation_result',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('task_id', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='测评任务id'),
    sa.Column('data_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='测评数据id'),
    sa.Column('result', mysql.TEXT(), nullable=True, comment='测评结果'),
    sa.Column('score', mysql.FLOAT(), nullable=True, comment='测评总体分数'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('evaluation_result', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_data_id'), ['data_id'], unique=False)

    op.create_table('memory_metadata',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('app_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='应用id'),
    sa.Column('vs_provider', mysql.VARCHAR(length=255), nullable=False, comment='vector_store provider'),
    sa.Column('vs_host', mysql.VARCHAR(length=255), nullable=False, comment='vector_store host'),
    sa.Column('vs_port', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='vector_store port'),
    sa.Column('vs_password', mysql.VARCHAR(length=255), nullable=True, comment='vector_store password'),
    sa.Column('vs_user', mysql.VARCHAR(length=255), nullable=True, comment='vector_store user name'),
    sa.Column('vs_collection_name', mysql.VARCHAR(length=255), nullable=False, comment='vector index name'),
    sa.Column('vs_embedding_model_dims', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='vector_store embedding dim'),
    sa.Column('llm_provider', mysql.VARCHAR(length=255), nullable=False, comment='llm provider'),
    sa.Column('llm_api_key', mysql.VARCHAR(length=255), nullable=False, comment='oneapi key'),
    sa.Column('llm_base_url', mysql.VARCHAR(length=255), nullable=True, comment='oneapi base url'),
    sa.Column('llm_model', mysql.VARCHAR(length=255), nullable=False, comment='oneapi model name'),
    sa.Column('embedder_provider', mysql.VARCHAR(length=255), nullable=False, comment='embedder provider'),
    sa.Column('embedder_api_key', mysql.VARCHAR(length=255), nullable=False, comment='embedder api key'),
    sa.Column('embedder_model', mysql.VARCHAR(length=255), nullable=False, comment='embedder model name'),
    sa.Column('embedder_base_url', mysql.VARCHAR(length=255), nullable=True, comment='embedder base url'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='is deleted'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('groups',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('ratio', mysql.FLOAT(), server_default=sa.text("'1'"), nullable=True),
    sa.Column('created', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('lastmodified', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_groups_name'), ['name'], unique=False)

    op.create_table('agent_project',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='唯一标识'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='项目名称'),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False, comment='描述'),
    sa.Column('owner', mysql.VARCHAR(length=255), nullable=False, comment='项目所有者'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='agent的项目属性',
    mysql_comment='agent的项目属性',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('agent_project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_owner'), ['owner'], unique=False)

    op.create_table('agent_tool_mapping',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='唯一标识'),
    sa.Column('agent_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='agent id'),
    sa.Column('tool_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='工具id'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='agent tool 映射关系',
    mysql_comment='agent tool 映射关系',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('agent_tool_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_tool_id'), ['tool_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_agent_id'), ['agent_id'], unique=False)

    op.create_table('training_task',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('task_type', mysql.VARCHAR(length=255), nullable=False, comment='任务类型'),
    sa.Column('task_status', mysql.VARCHAR(length=255), nullable=False, comment='任务状态'),
    sa.Column('task_progress', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='进度'),
    sa.Column('task_detail', mysql.VARCHAR(charset='utf8mb4', length=1024), nullable=True, comment='任务明细'),
    sa.Column('task_name', mysql.VARCHAR(length=255), nullable=False, comment='任务名称'),
    sa.Column('creator', mysql.VARCHAR(length=255), nullable=False, comment='创建人'),
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='团队ID'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='训练平台任务中心',
    mysql_comment='训练平台任务中心',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('training_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_group_creator'), ['group_id', 'creator'], unique=False)

    op.create_table('users',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('password', mysql.LONGTEXT(), nullable=False),
    sa.Column('display_name', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('role', mysql.BIGINT(display_width=20), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('status', mysql.BIGINT(display_width=20), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('github_id', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('wechat_id', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('access_token', mysql.CHAR(length=32), nullable=True),
    sa.Column('quota', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('used_quota', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('request_count', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('group', mysql.VARCHAR(length=32), server_default=sa.text("'default'"), nullable=True),
    sa.Column('aff_code', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('inviter_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('lark_id', mysql.VARCHAR(length=191), nullable=True),
    sa.Column('oidc_id', mysql.VARCHAR(length=191), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uni_users_username'), ['username'], unique=True)
        batch_op.create_index(batch_op.f('idx_users_we_chat_id'), ['wechat_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_oidc_id'), ['oidc_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_lark_id'), ['lark_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_inviter_id'), ['inviter_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_git_hub_id'), ['github_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('idx_users_aff_code'), ['aff_code'], unique=True)
        batch_op.create_index(batch_op.f('idx_users_access_token'), ['access_token'], unique=True)

    op.create_table('abilities',
    sa.Column('group', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('channel_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('priority', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('group', 'model', 'channel_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('abilities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_abilities_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('idx_abilities_channel_id'), ['channel_id'], unique=False)

    op.create_table('agent',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='唯一标识'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='agent 名称'),
    sa.Column('owner', mysql.VARCHAR(length=255), nullable=False, comment='agent 维护人'),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True, comment='agent描述'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.Column('min_threshold', mysql.FLOAT(), nullable=False, comment='选择tool的最低阈值'),
    sa.Column('top_tool_num', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='选择tool 的个数'),
    sa.Column('max_iterations', mysql.INTEGER(display_width=11), server_default=sa.text("'15'"), autoincrement=False, nullable=False, comment='最大迭代次数'),
    sa.Column('max_execution_time', mysql.INTEGER(display_width=11), server_default=sa.text("'120'"), autoincrement=False, nullable=False, comment='最大运行时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='agent 基本属性信息',
    mysql_comment='agent 基本属性信息',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('agent_scene',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='唯一标识'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='场景名称'),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True, comment='描述'),
    sa.Column('params', mysql.TEXT(), nullable=True, comment='场景的参数'),
    sa.Column('agent_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='场景关连的agent'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='agent 场景配置',
    mysql_comment='agent 场景配置',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('agent_input_format',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='格式名称，比如dwg, png, pdf'),
    sa.Column('params', mysql.TEXT(), nullable=True, comment='格式对应的参数'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='agent 支持的输入格式',
    mysql_comment='agent 支持的输入格式',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('agent_input_format', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_name'), ['name'], unique=False)

    op.create_table('render_task_pic_relation',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='主键自增id'),
    sa.Column('picid', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='图片id'),
    sa.Column('taskid', mysql.VARCHAR(length=128), nullable=False, comment='渲染任务id'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('render_task_pic_relation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_taskid'), ['taskid'], unique=True)
        batch_op.create_index(batch_op.f('idx_picid_taskid'), ['picid', 'taskid'], unique=True)

    op.create_table('evaluation_data',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False),
    sa.Column('input_query', mysql.VARCHAR(length=1024), nullable=False, comment='测评数据'),
    sa.Column('scene_id', mysql.BIGINT(display_width=20), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='对应测试集id'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('evaluation_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_scene_id'), ['scene_id'], unique=False)

    op.create_table('options',
    sa.Column('key', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('value', mysql.LONGTEXT(), nullable=True),
    sa.PrimaryKeyConstraint('key'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('agent_tool',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='唯一标识'),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False, comment='名称'),
    sa.Column('owner', mysql.VARCHAR(length=255), nullable=False, comment='tool 工具所有者'),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True, comment='描述'),
    sa.Column('template', mysql.TEXT(), nullable=True, comment='模板'),
    sa.Column('credentials', mysql.VARCHAR(length=1024), nullable=True, comment='访问凭证'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='agent的tool定义',
    mysql_comment='agent的tool定义',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('agent_tool', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_name'), ['name'], unique=False)

    op.create_table('llm_model_info',
    sa.Column('id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('model_name', mysql.VARCHAR(length=255), nullable=False, comment='LLM模型名称，如“ERNIE-Bot”'),
    sa.Column('display_name', mysql.VARCHAR(length=255), nullable=True, comment='用于展示给用户的别名，如“百度文心一言”'),
    sa.Column('one_api_token', mysql.VARCHAR(length=511), nullable=False, comment='one-api的接入token'),
    sa.Column('channel_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='one-api渠道id'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否已删除'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.Column('public', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否公开'),
    sa.Column('owner', mysql.VARCHAR(length=255), nullable=True, comment='owner的LDAP花名拼音'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('llm_model_info', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_oneapi_token'), ['one_api_token'], unique=False)
        batch_op.create_index(batch_op.f('idx_lastmodified'), ['lastmodified'], unique=False)
        batch_op.create_index(batch_op.f('idx_created'), ['created'], unique=False)

    op.create_table('agent_llm_mapping',
    sa.Column('id', mysql.BIGINT(display_width=20, unsigned=True), autoincrement=True, nullable=False, comment='唯一标识'),
    sa.Column('agent_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='agent id'),
    sa.Column('llm_model_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False, comment='模型id'),
    sa.Column('prompt', mysql.TEXT(), nullable=False, comment='大模型使用的prompt'),
    sa.Column('system', mysql.TEXT(), nullable=False, comment='大模型使用的system'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='agent llm 模型映射',
    mysql_comment='agent llm 模型映射',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('agent_llm_mapping', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idex_agent_id'), ['agent_id'], unique=False)

    op.create_table('vs_datasource_hivetask_relationship',
    sa.Column('datasource_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='数据源id'),
    sa.Column('hive_task_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=False, nullable=False, comment='hive任务id'),
    sa.Column('deleted', mysql.TINYINT(display_width=4), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='是否已删除'),
    sa.Column('created', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('lastmodified', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='最后修改时间'),
    sa.PrimaryKeyConstraint('datasource_id', 'hive_task_id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('vs_datasource_hivetask_relationship', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_hive_task_id'), ['hive_task_id'], unique=False)

    op.drop_table('ml_user_groups')
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_models_name'))
        batch_op.drop_index(batch_op.f('ix_ml_models_id'))

    op.drop_table('ml_models')
    with op.batch_alter_table('ml_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_api_keys_key'))
        batch_op.drop_index(batch_op.f('ix_ml_api_keys_id'))

    op.drop_table('ml_api_keys')
    with op.batch_alter_table('ml_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_users_username'))
        batch_op.drop_index(batch_op.f('ix_ml_users_email'))

    op.drop_table('ml_users')
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_providers_name'))

    op.drop_table('ml_providers')
    with op.batch_alter_table('ml_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_groups_name'))

    op.drop_table('ml_groups')
    # ### end Alembic commands ###
