"""Initial migration

Revision ID: 4a7e577f9ada
Revises: 
Create Date: 2026-03-10 10:05:26.234207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7e577f9ada'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_groups_name'), ['name'], unique=True)

    op.create_table('ml_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_providers_name'), ['name'], unique=True)

    op.create_table('ml_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_ml_users_username'), ['username'], unique=True)

    op.create_table('ml_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ml_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_api_keys_key'), ['key'], unique=True)

    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('context_size', sa.Integer(), nullable=True),
    sa.Column('input_size', sa.Integer(), nullable=True),
    sa.Column('input_price', sa.Float(), nullable=True),
    sa.Column('output_price', sa.Float(), nullable=True),
    sa.Column('cache_creation_price', sa.Float(), nullable=True),
    sa.Column('cache_hit_price', sa.Float(), nullable=True),
    sa.Column('support_kvcache', sa.Boolean(), nullable=True),
    sa.Column('support_image', sa.Boolean(), nullable=True),
    sa.Column('support_audio', sa.Boolean(), nullable=True),
    sa.Column('support_video', sa.Boolean(), nullable=True),
    sa.Column('support_file', sa.Boolean(), nullable=True),
    sa.Column('support_web_search', sa.Boolean(), nullable=True),
    sa.Column('support_tool_search', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ml_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_models_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_models_name'), ['name'], unique=False)

    op.create_table('ml_user_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['ml_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ml_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    # Note: Only creating ml_* tables, not dropping any existing tables
    # ### end Alembic commands ###


def downgrade():
    # ### Only drop ml_* tables that were created in upgrade() ###
    op.drop_table('ml_user_groups')

    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_models_name'))
        batch_op.drop_index(batch_op.f('ix_ml_models_id'))
    op.drop_table('ml_models')

    with op.batch_alter_table('ml_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_api_keys_key'))
        batch_op.drop_index(batch_op.f('ix_ml_api_keys_id'))
    op.drop_table('ml_api_keys')

    with op.batch_alter_table('ml_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_users_username'))
        batch_op.drop_index(batch_op.f('ix_ml_users_email'))
    op.drop_table('ml_users')

    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_providers_name'))
    op.drop_table('ml_providers')

    with op.batch_alter_table('ml_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_groups_name'))
    op.drop_table('ml_groups')
    # ### end Alembic commands ###
