"""add group_id to provider

Revision ID: 4b9c6d8e0f13
Revises: 3a8b5c7d9e12
Create Date: 2026-03-12 14:40:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b9c6d8e0f13'
down_revision = '3a8b5c7d9e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_ml_providers_group_id', 'ml_groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ml_providers_group_id', type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###