"""add support_transcription flag

Revision ID: 4d5f375e4b0e
Revises: 3a46d9278993
Create Date: 2026-08-06 14:27:40.585630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5f375e4b0e'
down_revision = '3a46d9278993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_model_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('support_transcription', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('support_transcription', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_column('support_transcription')

    with op.batch_alter_table('ml_model_templates', schema=None) as batch_op:
        batch_op.drop_column('support_transcription')

    # ### end Alembic commands ###
