"""add last sync id to api key

Revision ID: 6d7fbe925a04
Revises: 4409688c1128
Create Date: 2026-05-10 21:42:26.990341

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d7fbe925a04'
down_revision = '4409688c1128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables directly (MySQL batch mode fails on FK-backed indexes)
    op.drop_table('ml_group_permissions')
    op.drop_table('ml_workspace_permissions')

    with op.batch_alter_table('ml_api_key_budgets', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=20, scale=6),
               nullable=False)
        batch_op.alter_column('remaining',
               existing_type=mysql.DECIMAL(precision=20, scale=6),
               nullable=False)

    with op.batch_alter_table('ml_api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_stat_id', sa.BigInteger(), nullable=False))

    with op.batch_alter_table('ml_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_permission_group_key'))
        batch_op.drop_index(batch_op.f('ix_ml_permissions_key'))
        batch_op.create_index(batch_op.f('ix_ml_permissions_key'), ['key'], unique=True)

    with op.batch_alter_table('ml_users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_ml_users_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_users_id'))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('ml_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_permissions_key'))
        batch_op.create_index(batch_op.f('ix_ml_permissions_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('uq_permission_group_key'), ['key'], unique=True)

    with op.batch_alter_table('ml_api_keys', schema=None) as batch_op:
        batch_op.drop_column('last_stat_id')

    with op.batch_alter_table('ml_api_key_budgets', schema=None) as batch_op:
        batch_op.alter_column('remaining',
               existing_type=mysql.DECIMAL(precision=20, scale=6),
               nullable=True)
        batch_op.alter_column('amount',
               existing_type=mysql.DECIMAL(precision=20, scale=6),
               nullable=True)

    op.create_table('ml_workspace_permissions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('workspace_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('permission_key', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('is_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['ml_workspaces.id'], name=op.f('ml_workspace_permissions_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ml_workspace_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_workspace_permission'), ['workspace_id', 'permission_key'], unique=True)

    op.create_table('ml_group_permissions',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('group_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('permission_key', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('is_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ml_groups.id'], name=op.f('ml_group_permissions_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ml_group_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_group_permission'), ['group_id', 'permission_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_ml_group_permissions_permission_key'), ['permission_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_group_permissions_group_id'), ['group_id'], unique=False)

    # ### end Alembic commands ###
