"""sync model-link tables only

Revision ID: 86f5002e4369
Revises: 3a8b5c7d9e12
Create Date: 2026-03-12 11:32:30.528574

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86f5002e4369'
down_revision = '3a8b5c7d9e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_ml_models_alias'))

    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.alter_column('type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_ml_models_alias'), ['alias'], unique=True)

    # ### end Alembic commands ###
