"""initial migration

Revision ID: 8e60ad08d84d
Revises: 
Create Date: 2026-05-11 18:33:38.793789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e60ad08d84d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_background_responses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('response_id', sa.String(length=100), nullable=False),
    sa.Column('apikey', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('input_key', sa.String(length=500), nullable=True),
    sa.Column('output_key', sa.String(length=500), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_background_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_background_responses_response_id'), ['response_id'], unique=True)

    op.create_table('ml_model_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('context_size', sa.Integer(), nullable=True),
    sa.Column('input_size', sa.Integer(), nullable=True),
    sa.Column('output_size', sa.Integer(), nullable=True),
    sa.Column('reasoning_effort', sa.String(length=20), nullable=True),
    sa.Column('supported_image_formats', sa.Text(), nullable=True),
    sa.Column('pricing_tiers', sa.JSON(), nullable=True),
    sa.Column('output_pricing', sa.JSON(), nullable=True),
    sa.Column('input_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('output_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('cache_creation_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('cache_5m_creation_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('cache_1h_creation_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('cache_hit_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('retirement_time', sa.DateTime(), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('support_kvcache', sa.Boolean(), nullable=True),
    sa.Column('support_image', sa.Boolean(), nullable=True),
    sa.Column('support_audio', sa.Boolean(), nullable=True),
    sa.Column('support_video', sa.Boolean(), nullable=True),
    sa.Column('support_file', sa.Boolean(), nullable=True),
    sa.Column('support_web_search', sa.Boolean(), nullable=True),
    sa.Column('support_tool_search', sa.Boolean(), nullable=True),
    sa.Column('support_thinking', sa.Boolean(), nullable=True),
    sa.Column('support_online_image', sa.Boolean(), nullable=True),
    sa.Column('support_online_video', sa.Boolean(), nullable=True),
    sa.Column('support_embedding', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_model_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_model_templates_id'), ['id'], unique=False)

    op.create_table('ml_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('allowed_roles', sa.JSON(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_permissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_permissions_key'), ['key'], unique=True)

    op.create_table('ml_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'value', name='uq_tag_name_value')
    )
    with op.batch_alter_table('ml_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_tags_name'), ['name'], unique=False)

    op.create_table('ml_usage_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('api_key_hash', sa.String(length=64), nullable=True),
    sa.Column('api_key_preview', sa.String(length=20), nullable=True),
    sa.Column('api_key_name', sa.String(length=100), nullable=True),
    sa.Column('model_name', sa.String(length=200), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('input_price_unit', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_price_unit', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('cache_creation_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cache_creation_price_unit', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('cache_5m_creation_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cache_5m_creation_price_unit', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('cache_1h_creation_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cache_1h_creation_price_unit', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('cache_tokens', sa.BigInteger(), nullable=True),
    sa.Column('cache_token_price_unit', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('reasoning_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_image_number', sa.Integer(), nullable=True),
    sa.Column('output_image_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_image_resolution', sa.String(length=50), nullable=True),
    sa.Column('output_image_aspect', sa.String(length=20), nullable=True),
    sa.Column('output_image_price_unit', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('output_video_number', sa.Integer(), nullable=True),
    sa.Column('output_video_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_video_resolution', sa.String(length=50), nullable=True),
    sa.Column('output_video_aspect', sa.String(length=20), nullable=True),
    sa.Column('output_video_seconds', sa.Float(), nullable=True),
    sa.Column('output_video_price_unit', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('output_audio_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_audio_seconds', sa.Float(), nullable=True),
    sa.Column('output_audio_price_unit', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('web_search_requests', sa.Integer(), nullable=True),
    sa.Column('web_search_price_unit', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('credits', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('credit_price_unit', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('payable_amount', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('actual_amount', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('actual_amount_usd', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_usage_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_usage_records_api_key_hash'), ['api_key_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_usage_records_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_usage_records_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_usage_records_group_name'), ['group_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_usage_records_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_usage_records_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_usage_records_provider_name'), ['provider_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_usage_records_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_usage_records_user_name'), ['user_name'], unique=False)

    op.create_table('ml_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_ml_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_users_username'), ['username'], unique=True)

    op.create_table('ml_workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_workspaces_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_workspaces_name'), ['name'], unique=True)

    op.create_table('ml_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.Column('monitoring_config', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['ml_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_groups_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_ml_groups_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('ml_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('total_input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_reasoning_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('total_image_count', sa.Integer(), nullable=True),
    sa.Column('total_video_count', sa.Integer(), nullable=True),
    sa.Column('total_audio_seconds', sa.Float(), nullable=True),
    sa.Column('last_stat_id', sa.BigInteger(), nullable=False),
    sa.Column('allowed_models', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('unlimited_budget', sa.Boolean(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ml_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ml_users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['ml_workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_api_keys_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_api_keys_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_ml_api_keys_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_api_keys_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('ml_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('authorization', sa.String(length=50), nullable=True),
    sa.Column('extra_config', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['ml_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'group_id', name='uq_provider_name_group')
    )
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_providers_name'), ['name'], unique=False)

    op.create_table('ml_user_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['ml_groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['ml_users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('ml_api_key_budgets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('api_key_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('remaining', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['ml_api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_api_key_budgets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_api_key_budgets_api_key_id'), ['api_key_id'], unique=False)

    op.create_table('ml_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('alias', sa.String(length=100), nullable=True),
    sa.Column('context_size', sa.Integer(), nullable=True),
    sa.Column('input_size', sa.Integer(), nullable=True),
    sa.Column('output_size', sa.Integer(), nullable=True),
    sa.Column('input_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('output_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('reasoning_effort', sa.String(length=20), nullable=True),
    sa.Column('supported_image_formats', sa.Text(), nullable=True),
    sa.Column('pricing_tiers', sa.JSON(), nullable=True),
    sa.Column('output_pricing', sa.JSON(), nullable=True),
    sa.Column('cache_creation_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('cache_5m_creation_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('cache_1h_creation_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('cache_hit_price', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('retirement_time', sa.DateTime(), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('discount', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('traffic_ratio', sa.Integer(), nullable=False),
    sa.Column('support_kvcache', sa.Boolean(), nullable=True),
    sa.Column('support_image', sa.Boolean(), nullable=True),
    sa.Column('support_audio', sa.Boolean(), nullable=True),
    sa.Column('support_video', sa.Boolean(), nullable=True),
    sa.Column('support_file', sa.Boolean(), nullable=True),
    sa.Column('support_web_search', sa.Boolean(), nullable=True),
    sa.Column('support_tool_search', sa.Boolean(), nullable=True),
    sa.Column('support_thinking', sa.Boolean(), nullable=True),
    sa.Column('support_online_image', sa.Boolean(), nullable=True),
    sa.Column('support_online_video', sa.Boolean(), nullable=True),
    sa.Column('support_embedding', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['ml_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_models_alias'), ['alias'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_models_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_models_name'), ['name'], unique=False)

    op.create_table('ml_workspace_rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('tpm', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['ml_providers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['ml_workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'model_name', 'provider_type', 'provider_id', name='uq_workspace_model_provider_rate_limit')
    )
    with op.batch_alter_table('ml_workspace_rate_limits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_workspace_rate_limits_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_workspace_rate_limits_model_name'), ['model_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_workspace_rate_limits_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_workspace_rate_limits_provider_type'), ['provider_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_ml_workspace_rate_limits_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('ml_model_shares',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('source_group_id', sa.Integer(), nullable=False),
    sa.Column('target_group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['ml_users.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['ml_models.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_group_id'], ['ml_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_group_id'], ['ml_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_id', 'target_group_id', name='uq_model_share_target')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ml_model_shares')
    with op.batch_alter_table('ml_workspace_rate_limits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_workspace_rate_limits_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_ml_workspace_rate_limits_provider_type'))
        batch_op.drop_index(batch_op.f('ix_ml_workspace_rate_limits_provider_id'))
        batch_op.drop_index(batch_op.f('ix_ml_workspace_rate_limits_model_name'))
        batch_op.drop_index(batch_op.f('ix_ml_workspace_rate_limits_id'))

    op.drop_table('ml_workspace_rate_limits')
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_models_name'))
        batch_op.drop_index(batch_op.f('ix_ml_models_id'))
        batch_op.drop_index(batch_op.f('ix_ml_models_alias'))

    op.drop_table('ml_models')
    with op.batch_alter_table('ml_api_key_budgets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_api_key_budgets_api_key_id'))

    op.drop_table('ml_api_key_budgets')
    op.drop_table('ml_user_groups')
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_providers_name'))

    op.drop_table('ml_providers')
    with op.batch_alter_table('ml_api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_api_keys_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_ml_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_ml_api_keys_key'))
        batch_op.drop_index(batch_op.f('ix_ml_api_keys_id'))

    op.drop_table('ml_api_keys')
    with op.batch_alter_table('ml_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_groups_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_ml_groups_name'))

    op.drop_table('ml_groups')
    with op.batch_alter_table('ml_workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_workspaces_name'))
        batch_op.drop_index(batch_op.f('ix_ml_workspaces_id'))

    op.drop_table('ml_workspaces')
    with op.batch_alter_table('ml_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_users_username'))
        batch_op.drop_index(batch_op.f('ix_ml_users_id'))
        batch_op.drop_index(batch_op.f('ix_ml_users_email'))

    op.drop_table('ml_users')
    with op.batch_alter_table('ml_usage_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_usage_records_user_name'))
        batch_op.drop_index(batch_op.f('ix_ml_usage_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_ml_usage_records_provider_name'))
        batch_op.drop_index(batch_op.f('ix_ml_usage_records_provider_id'))
        batch_op.drop_index(batch_op.f('ix_ml_usage_records_model_name'))
        batch_op.drop_index(batch_op.f('ix_ml_usage_records_group_name'))
        batch_op.drop_index(batch_op.f('ix_ml_usage_records_group_id'))
        batch_op.drop_index(batch_op.f('ix_ml_usage_records_created_at'))
        batch_op.drop_index(batch_op.f('ix_ml_usage_records_api_key_hash'))

    op.drop_table('ml_usage_records')
    with op.batch_alter_table('ml_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_tags_name'))

    op.drop_table('ml_tags')
    with op.batch_alter_table('ml_permissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_permissions_key'))

    op.drop_table('ml_permissions')
    with op.batch_alter_table('ml_model_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_model_templates_id'))

    op.drop_table('ml_model_templates')
    with op.batch_alter_table('ml_background_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_background_responses_response_id'))

    op.drop_table('ml_background_responses')
    # ### end Alembic commands ###
