"""add_background_responses_table

Revision ID: 92ea386ad62e
Revises: 0f45452122a5
Create Date: 2026-03-29 14:53:47.655804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ea386ad62e'
down_revision = '0f45452122a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_background_responses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('response_id', sa.String(length=100), nullable=False),
    sa.Column('apikey', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('input_key', sa.String(length=500), nullable=True),
    sa.Column('output_key', sa.String(length=500), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ml_background_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ml_background_responses_response_id'), ['response_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_background_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_background_responses_response_id'))

    op.drop_table('ml_background_responses')
    # ### end Alembic commands ###
