"""add rpm and tpm to api_keys

Revision ID: a24dfff4aa94
Revises: 8e60ad08d84d
Create Date: 2026-05-12 22:05:33.200383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24dfff4aa94'
down_revision = '8e60ad08d84d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rpm', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tpm', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_api_keys', schema=None) as batch_op:
        batch_op.drop_column('tpm')
        batch_op.drop_column('rpm')

    # ### end Alembic commands ###
