"""add service_tiers to models and service_tier to usage records

Revision ID: b989821db7b2
Revises: cc1ac955c975
Create Date: 2026-08-05 08:55:22.671740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b989821db7b2'
down_revision = 'cc1ac955c975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_tiers', sa.JSON(), nullable=True))

    with op.batch_alter_table('ml_usage_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_tier', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_usage_records', schema=None) as batch_op:
        batch_op.drop_column('service_tier')

    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_column('service_tiers')

    # ### end Alembic commands ###
