"""add last_synced_remaining, total_web_search_requests, total_credits to ApiKey

Revision ID: c06b5f30e164
Revises: 73e751a720bc
Create Date: 2026-05-16 21:09:55.707803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06b5f30e164'
down_revision = '73e751a720bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_api_keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_web_search_requests', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_credits', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_synced_remaining', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_api_keys', schema=None) as batch_op:
        batch_op.drop_column('last_synced_remaining')
        batch_op.drop_column('total_credits')
        batch_op.drop_column('total_web_search_requests')

    # ### end Alembic commands ###
