"""widen_supported_image_formats_field

Revision ID: c724707f0df2
Revises: 1f90c0ba0b8c
Create Date: 2026-04-12 13:09:33.793709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c724707f0df2'
down_revision = '1f90c0ba0b8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_model_templates', schema=None) as batch_op:
        batch_op.alter_column('supported_image_formats',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.alter_column('supported_image_formats',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.alter_column('supported_image_formats',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    with op.batch_alter_table('ml_model_templates', schema=None) as batch_op:
        batch_op.alter_column('supported_image_formats',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###
