"""add support_tts flag

Revision ID: cc1ac955c975
Revises: 497ad4adde1f
Create Date: 2026-07-31 09:21:26.648439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1ac955c975'
down_revision = '497ad4adde1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_model_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('support_tts', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('support_tts', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_models', schema=None) as batch_op:
        batch_op.drop_column('support_tts')

    with op.batch_alter_table('ml_model_templates', schema=None) as batch_op:
        batch_op.drop_column('support_tts')

    # ### end Alembic commands ###
