"""sync database structure

Revision ID: e1ceb4665f19
Revises: 041c7168af5e
Create Date: 2026-03-22 17:39:23.560811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1ceb4665f19'
down_revision = '041c7168af5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_config', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_providers', schema=None) as batch_op:
        batch_op.drop_column('extra_config')

    # ### end Alembic commands ###
