"""make uploaded file id non unique per provider

Revision ID: e36f69b23f68
Revises: 4d5f375e4b0e
Create Date: 2026-08-13 17:33:30.510674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e36f69b23f68'
down_revision = '4d5f375e4b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_uploaded_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ml_uploaded_files_file_id'))
        batch_op.create_index(batch_op.f('ix_ml_uploaded_files_file_id'), ['file_id'], unique=False)
        batch_op.create_unique_constraint('uq_uploaded_file_provider', ['file_id', 'provider_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ml_uploaded_files', schema=None) as batch_op:
        batch_op.drop_constraint('uq_uploaded_file_provider', type_='unique')
        batch_op.drop_index(batch_op.f('ix_ml_uploaded_files_file_id'))
        batch_op.create_index(batch_op.f('ix_ml_uploaded_files_file_id'), ['file_id'], unique=True)

    # ### end Alembic commands ###
